coordination_experiments/Controllers control_mode
coordination_experiments/Inputs input_mode
float64 abs_alpha
float64 rel_alpha

---
---
float64 joint_space_norm
float64 relative_error_norm
float64 relative_error_angle
geometry_msgs/Point relative_error
float64[] absolute_velocity
float64[] relative_velocity
