coordination_experiments/Controllers control_mode
coordination_experiments/Inputs input_mode
coordination_experiments/WorkspaceLimits limits
float64 max_time
float64 alpha
bool dynamic_alpha
---
---
float64 curr_alpha
float64 absolute_angle
float64 obj1_angle
float64 obj2_angle
float64 joint_space_norm
float64 relative_error_norm
float64 relative_error_angle
geometry_msgs/Point relative_error
geometry_msgs/Point absolute_position
