kinematic_chain_base_link: torso
max_tf_attempts: 5
max_joint_pos_error: 0.1
loop_rate: 1000
left_obj_frame: left_object
right_obj_frame: right_object

relative_gain:
  data: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

eef1:
  kdl_eef_frame: left_gripper
  gripping_frame: left_gripper
  has_ft_sensor: false
  sensor_frame: ""
  sensor_topic: ""

eef2:
  kdl_eef_frame: right_gripper
  gripping_frame: right_gripper
  has_ft_sensor: false
  sensor_frame: ""
  sensor_topic: ""


marker_servers: ['relative_motion_markers', 'absolute_motion_markers']

relative_motion_markers:
  marker_names: ['obj1', 'obj2']

  obj1:
    parent_frame: 'left_gripper'
    name: 'left_object'
    initial_pose: [0, 0, 0, -0.707, 0.0, 0, 0.707]

  obj2:
    parent_frame: 'right_gripper'
    name: 'right_object'
    initial_pose: [0, 0, 0, 0.707, 0.0, 0.0, 0.707]

absolute_motion_markers:
  marker_names: ['absolute_pose']

  absolute_pose:
    parent_frame: 'base'
    name: 'absolute_pose'
    initial_pose: [0.7, 0.0, 0.5, 0, 0, 0, 1]
