kinematic_chain_base_link: torso
max_tf_attempts: 5
max_joint_pos_error: 0.1
loop_rate: 100

eef1:
  kdl_eef_frame: left_gripper
  gripping_frame: left_gripper
  has_ft_sensor: false
  sensor_frame: ""
  sensor_topic: ""

eef2:
  kdl_eef_frame: right_gripper
  gripping_frame: right_gripper
  has_ft_sensor: false
  sensor_frame: ""
  sensor_topic: ""
