kinematic_chain_base_link: torso
max_tf_attempts: 5
max_joint_pos_error: 0.1
loop_rate: 50
left_obj_frame: obj1
right_obj_frame: obj2

relative_gain:
  data: [0.5, 0.0, 0.0, 0.0, 0.0, 0.0,
         0.0, 0.5, 0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.5, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

eef1:
  kdl_eef_frame: left_gripper
  gripping_frame: left_gripper
  has_ft_sensor: false
  sensor_frame: ""
  sensor_topic: ""

eef2:
  kdl_eef_frame: right_gripper
  gripping_frame: right_gripper
  has_ft_sensor: false
  sensor_frame: ""
  sensor_topic: ""
